### PR TITLE
Fixed child views overlapping with parallaxed view in ScrollView, if …

### LINKED ISSUE #59: ParallaxScrollView will make child views overlap with parallax view if child views' bg are transparent
ParallaxScrollView works great, but only if child views have a solid background, which is able to cover the parallaxed view.

If my child views (which are not parallaxed) have transparent background (e.g. I have a background image underneath, so my views need to be transparent), child views will appear on top of the parallaxed view.

I have managed to solve this by applying a rectangular clip, but only applicable to:
(1) ScrollView only
(2) API level > 18 (since View.clipBounds() need API level > 18)

I plan to submit a pull request later.

### PR DESCRIPTION
**Pull request by lsw19921030**
…background is transparent.

Fixed #59

### CODE REVIEW

File: ParallaxScroll/src/com/nirhart/parallaxscroll/views/ParallaxedView.java [hunk 1]
```diff
@@ -40,6 +43,35 @@ public void setOffset(float offset) {
...
+        if (view != null)
+            if (isAPI11) {
+                if (!firstRectGet) {
+                    clippingRect.top = view.getTop();
+                    clippingRect.left = view.getLeft();
+                    clippingRect.right = view.getRight();
+                    clippingRect.bottom = view.getBottom();
+                    firstRectGet = true;
+                }
+                int delta = lastScrollY - originalScrollY;
```
Comment (thebestpol) [inline ParallaxScroll/src/com/nirhart/parallaxscroll/views/ParallaxedView.java]: lastScrollY is not declared

File: ParallaxScroll/src/com/nirhart/parallaxscroll/views/ParallaxedView.java [hunk 2]
```diff
@@ -13,9 +13,12 @@
 
 public abstract class ParallaxedView {
 	static public boolean isAPI11 = Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB;
+	static public boolean isAPI18 = Build.VERSION.SDK_INT >= 18;
 	protected WeakReference<View> view;
 	protected int lastOffset;
 	protected List<Animation> animations;
+	protected Rect clippingRect = new Rect();
```
Comment (thebestpol) [inline ParallaxScroll/src/com/nirhart/parallaxscroll/views/ParallaxedView.java]: And this class is not imported
